import { Favoris, Category, Post, Widget } from '../components'
import Link from 'next/link'
import { getPosts, getCategories, getRecentPosts, getRecentSold } from '../services'

import Head from 'next/head'
// import Image from 'next/image'





export default function Home({ posts, categories, recentPosts, recentSold }) {

  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Vinyl Touch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => <Post key={post.title} post={post.node} />)}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">

            <Category key={categories.title} post={categories} />

            <Widget key={recentPosts.title} post={recentPosts} />

            <Favoris key={recentSold.author} post={recentSold} />
          </div>


        </div>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const posts = (await getPosts());

  const categories = (await getCategories());


  const recentPosts = (await getRecentPosts());

  const recentSold = (await getRecentSold());

  return {
    props: { posts, categories, recentPosts, recentSold },
  }

}


